### ISSUE TITLE
haproxy 启用 tcp fast open

### ISSUE THREAD

**Issue by hhding** [nanqinlang/sometimesnaiveorg#151]
haproxy 启用 tcp fast open 需要在配置里面显式指定
譬如：bind *:12345 tfo
请在安装脚本上加上支持。

谢谢

**Comment by nanqinlang** [comment]
这样啊。之后加上

**Comment by nanqinlang** [comment]
还有，这个 issue 你开错位置了。我会 close 这个。

也可能那边我 archive 了你才来这里开的。

我新开了 issue 放在 https://github.com/tcp-nanqinlang/lkl-haproxy/issues/2
